
# Automatically generated by /home/mshafae/github/cpsc120/cpsc-120-solution-lab-02/.action/ccsrcutilities.py on 2024-09-03 11:56:37

TOPTARGETS = all clean spotless format lint authors test unittest

SUBDIRS = $(wildcard part-?/.)

default all: all

$(TOPTARGETS): $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -f .Makefile -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)

