
#include <Magick++.h>

#include <iostream>
#include <string>
#include <vector>

#include "make_message_functions.h"

/// Main function - Entry point for our ray tracer
/// The program takes two arguments which is the output file name and a
/// a brief message. The image generated by the main function is written
/// out as a GIF file.
int main(int argc, char const* argv[]) {
  Magick::InitializeMagick(*argv);
  std::vector<std::string> command{argv, argv + argc};
  if (command.size() < 2) {
    std::cout << "Please provide a path to a file\n";
    return 1;
  }

  std::string output_file_name{command.at(1)};

  std::string image_format{".gif"};
  if (!HasMatchingFileExtension(output_file_name, image_format)) {
    std::cout << "/foobar is missing the required file extension .gif.\n";
    return 1;
  }

  std::string message{command.at(2)};

  const double aspect_ratio = 16.0 / 9.0;
  // Set the image width to 1024 pixels
  const int image_width = 1024;
  // Calculate the height of the image using the width and aspect ratio.
  // Remember to round the number to the closest integer.
  const int image_height =
      static_cast<int>(std::lround(image_width / aspect_ratio));
  Magick::ColorRGB yellow(1, 1, 0);
  Magick::Image image(Magick::Geometry(image_width, image_height), yellow);
  // Print out some information about the image to help us debug what's
  // going on.
  std::cout << "Your image has " << image.columns()
            << " columns (x direction) and " << image.rows()
            << " rows (y direction).\n";

  const int number_of_images = 5;
  std::vector<Magick::Image> images;

  for (int image_count = 0; image_count < number_of_images; image_count++) {
    std::cerr << "Image " << image_count + 1 << "...";

    // TODO: Create an inner and outer loop to visit each pixel.
    // For example:
    for (int row = 0; row < image.rows(); row++) {
      for (int column = 0; column < image.columns(); column++) {
        double random_color_intensity{RandomDouble01()};
        double red{0.0};
        double green{0.0};
        double blue{0.0};
        if (CoinFlip()) {
          red = random_color_intensity;
        }
        if (CoinFlip()) {
          green = random_color_intensity;
        }
        if (CoinFlip()) {
          blue = random_color_intensity;
        }
        Magick::ColorRGB color{red, green, blue};
        image.pixelColor(column, row, color);
      }
    }

    image.font(kMessageFont);
    image.fontPointsize(image.rows() / 3.0);
    image.fillColor(Magick::Color("yellow"));
    image.annotate(message, Magick::CenterGravity);

    images.push_back(image);
    std::cerr << "completed.\n";
  }

  Magick::writeImages(images.begin(), images.end(), output_file_name);

  return 0;
}
